remote_theme: pages-themes/slate@v0.2.0
title: COMP6741 @ UNSW
description: Course webpage for COMP6741 Algorithms for Intractable Problems
show_downloads: false
google_analytics: m7NV2-N9eLSLB48RR2pTjYTyvn2ldN_ovMDM53Wj1-U

plugins:
- jekyll-remote-theme
